### PR TITLE
Switch component

### PR DESCRIPTION
**Pull request by KirilNN**

### CODE REVIEW

**Comment by underlog** [comment]
Spotted the following issues:

- Drag the switch to the right beyond the component area, then bring it back a little. It toggles back to "OFF" state, which is not expected.
- The component is missing a focused styling indicator. 
- I think that the keyboard shortcuts implementation should match that of the checkbox - where pressing space toggles the component state. Please research that.

**Comment by KirilNN** [comment]
@underlog  thanks for the update. The dragging behavior is now fixed, as for the keyboard - it looks like `space` and `enter` keys should toggle the state, so I have changed the implementation.

Waiting for @gyoshev for the focused styling indicator

**Comment by KirilNN** [comment]
So we agreed on moving the `animations` outside the model, and using the `updateState` function directly through the callback. 

Will work on that and update as soon as any progress is made.

**Comment by KirilNN** [comment]
any updates here @rkonstantinov @underlog

**Pull request merged**
