### PR TITLE
docs: add CSS information about the package

### PR DESCRIPTION
**Pull request by KirilNN**
@underlog please take a look and let me know if any changes are needed. 

Thanks

### CODE REVIEW

**Comment by underlog** [comment]
Shipping CSS files in a React component is not a standard approach. Most of the toolkits out there rely on inline styilng. 

Given that, an example that shows the possible approaches will be necessary. We can host these in the `examples` directory.

**Comment by cosminnicula** [comment]
Inline styles are a delicate subject - you can see some details on this subject here https://github.com/callemall/material-ui/issues/1951

**Comment by underlog** [comment]
@cosminnicula Thanks for chimming in. We are hesitant to go into the inline styles direction. The Kendo UI react components are compatible with the existing Kendo UI themes, so we are using the same CSS classes.

**Comment by cosminnicula** [comment]
It might be a good idea though to have the CSS delivered as modular files (one file per component) and also to have support for namespacing (e.g. Sass variables in selectors through interpolation – .#{$css-prefix}).

**Comment by KirilNN** [comment]
@cosminnicula currently if you include more than one component styling in your project the CSS output might get duplicate values. We are currently working on a solution for this as well as better documentation about it.

**Pull request closed without merging**
